- README.md
> Add note about credentials we can use

- .eslintrc.js
- src/Components/Released/released.tsx
- src/Components/ReleasedViewToolbar/CustomDropdown.tsx
- src/Components/ReleasedViewToolbar/CustomToggleGroup.tsx
- src/constants.ts
Preparing dummy components based on mocks, we will give them life during next weeks.
[Screencast from 2024-10-30 17-24-23.webm](https://github.com/user-attachments/assets/cf326ec0-5af0-4090-92fe-733f9738ab57)
> Add dummy components to Released tab

- jest.config.js
- package-lock.json
- package.json
- src/App.scss
- src/Components/Lifecycle/lifecycle.tsx
- src/Components/LifecycleChart/lifecycleChart.tsx
- src/Components/LifecycleFilters/LifecycleFilters.test.tsx
- src/Components/LifecycleFilters/LifecycleFilters.tsx
- src/Components/LifecycleFilters/lifecycleFilters.scss
- src/Components/LifecycleTable/lifecycleTable.tsx
- src/types/ErrorObject.ts
Add name filter and basic layout for filters component. Configured repo to show test coverage. Added test for name filter.
[RSPEED-513](https://issues.redhat.com/browse/RSPEED-513)
---
---
##
##
> Add name filter to lifecycle section 

- .tekton/pipeline-build.yaml
Add args to the Snyk scan task so that the scan results are uploaded.
> Upload Snyk scans

- src/Components/AppLifecycleTable/appLifecycleTable.tsx
- src/Components/Lifecycle/lifecycle.tsx
- src/types/AppLifecycleChanges.ts
- src/types/Profile.ts
- src/types/Stream.ts
This PR adds app streams data into the UI. Will be followed by switching using the dropdown.
[RSPEED-508](https://issues.redhat.com/browse/RSPEED-508)
---
---
##
##
> [RSPEED-508] Load the data from App Stream lifecycle api to frontend

- src/App.scss
- src/Components/LifecycleChart/lifecycleChart.scss
- src/Components/LifecycleChart/lifecycleChart.tsx
Adjust chart to better match designs.
[RSPEED-520](https://issues.redhat.com/browse/RSPEED-520)
[RSPEED-526](https://issues.redhat.com/browse/RSPEED-526)
---
---
##
##
> fix(LifecycleChart): Make full-width

- src/Components/LifecycleTable/LifecycleTable.tsx
Adds pagination to tables.
[RSPEED-514](https://issues.redhat.com/browse/RSPEED-514)
---
---
##
##
> Pagination

- src/Components/LifecycleTable/LifecycleTable.tsx
- src/types/SystemLifecycleChanges.ts
Pagination should be based on sorted data. Lifting sorting up into state so we can use it for pagination.
Jira link:
---
---
##
##
> fix(LifecycleTable): Adjust sorting/pagination

- src/Components/LifecycleChart/LifecycleChart.tsx
We used to always show 2020-2033 regardless of actual data.
This allows us to dynamically generate x axis dates based on actual data. We fill in interstitial values and always end with January of the last year of the data set.
Jira link:
---
---
##
##
> feat(LifecycleChart): Make x axis dates dynamic

- src/Components/LifecycleTable/LifecycleTable.tsx
Remove Release column from RHEL.
Jira link:
---
---
##
##
> fix(LifecycleTable): Drop RHEL release column

- fec.config.js
- src/constants.ts
Fix api names which were changed in
https://github.com/RedHatInsights/digital-roadmap-backend/pull/40
Jira link:
---
---
##
##
> Fix api names

- src/Components/LifecycleChart/LifecycleChart.tsx
This PR adds a vertical line along the x axis to represent the current date on the Lifecycle Chart.
Jira link:
---
---
##
##
> Add vertical line to Lifecycle Chart

- src/Components/LifecycleTable/LifecycleTable.tsx
Makes it less jumpy on sort.
Jira link:
---
---
##
##
> fix(LifecycleTable): Add maxWidth to name column

- src/Components/FilterComponents/LifecycleDropdown.tsx
- src/Components/Lifecycle/Lifecycle.tsx
- src/Components/LifecycleFilters/LifecycleFilters.scss
- src/Components/LifecycleFilters/LifecycleFilters.test.tsx
- src/Components/LifecycleFilters/LifecycleFilters.tsx
Added view toggle group. Also moved dropdown into filter component and styled everything.
Jira link:
---
---
##
##
> feat(LifecycleFilters): Add view toggle group

- src/Components/Lifecycle/Lifecycle.tsx
- src/Components/LifecycleTable/LifecycleTable.tsx
- src/constants.ts
- src/types/SystemLifecycleChanges.ts
This PR updates the frontend tab to accept the new formats for data coming from the backend api. We have removed the release field from the RHEL system data and renamed the `systems` field to `count`. The RHEL systems data is now wrapped in a `data` array so the data fetch has been updated to accommodate that. 
Jira link:
---
---
##
##
> Update Lifecycle tab to accept backend changes

- jest.config.js
- src/Components/Lifecycle/Lifecycle.tsx
- src/Components/Lifecycle/filteringUtils.test.ts
- src/Components/Lifecycle/filteringUtils.ts
- src/Components/LifecycleChart/LifecycleChart.tsx
- src/Components/LifecycleFilters/LifecycleFilters.scss
- src/Components/LifecycleFilters/LifecycleFilters.test.tsx
- src/Components/LifecycleFilters/LifecycleFilters.tsx
- src/__mocks__/mockData.ts
Add chart filtering dropdown, hook up chart filtering, and fix tooltip for date line.
Jira link:
[RSPEED-516](https://issues.redhat.com/browse/RSPEED-516)
---
---
##
##
> feat(ChartFilter): Add UI components for chart filter

- src/__mocks__/mockData.ts
> Update mock data fields for tests

- src/constants.ts
This PR updates the constants.ts file to have the proper api paths for our api calls.
Jira link:
---
---
##
##
> Update api constants

- .codecov.yml
- .github/workflows/ci.yaml
- README.md
- jest.config.js
Add GitHub actions to run sanity and unit tests, generate coverage report, and upload to CodeCov.
> Generate and upload coverage report

- src/Components/LifecycleFilters/LifecycleFilters.test.tsx
- src/Components/LifecycleFilters/LifecycleFilters.tsx
- src/Components/LifecycleTable/LifecycleTable.tsx
- src/Components/UpcomingRow/UpcomingRow.tsx
- src/Components/UpcomingTable/UpcomingTableFilters.tsx
Filter placeholder name differed from mocks. Some other cleanup also while I'm in here.
Jira link:
---
---
##
##
> Adjust filter placeholder name

- src/AppEntry.tsx
- src/Components/AppLink/index.tsx
- src/Components/FilterComponents/CustomDropdown.tsx
- src/Components/Lifecycle/Lifecycle.tsx
- src/Components/Released/released.tsx
- src/Components/ReleasedView/ReleasedView.tsx
- src/Components/SystemInfoCard/SystemInfoCard.tsx
- src/Components/Upcoming/mock_data.ts
- src/Components/UpcomingTable/UpcomingTableFilters.tsx
- src/Routing.tsx
- src/api.ts
- src/bootstrap.tsx
- src/types/UpcomingChanges.ts
Just clearing up prettier issues.
Jira link:
---
---
##
##
> chore(linter): Fix all prettier issues

- src/Components/LifecycleFilters/LifecycleFilters.tsx
- src/Routes/LandingPage/LandingPage.tsx
Change spacing on term
Jira link:
---
---
##
##
> Change Lifecycle to Life Cycle or Life cycle per mocks

- src/Components/Upcoming/Upcoming.tsx
- src/Components/UpcomingTable/UpcomingTable.tsx
Allow for sorting table columns.
Jira link:
---
---
##
##
> feat(Upcoming): Add sorting

- package-lock.json
- package.json
- src/Components/Lifecycle/Lifecycle.tsx
- src/Components/LifecycleFilters/LifecycleFilters.scss
- src/Components/LifecycleFilters/LifecycleFilters.test.tsx
- src/Components/LifecycleFilters/LifecycleFilters.tsx
- src/Components/LifecycleTable/LifecycleTable.tsx
- src/utils/utils.ts
Add CSV download functionality.
Jira link:
---
https://github.com/user-attachments/assets/1b517182-fd2f-4c31-ae21-04d48b71ab97
---
##
##
> feat(Lifecycle): Add CSV download

- src/Components/Lifecycle/Lifecycle.tsx
Add data structure that can be used to build filter URLs.
Jira link:
---
---
##
##
> chore(Lifecycle): Add data structure for most basic filter tracking

- deploy/frontend.yaml
Add routes and correct image.
I am not 100% sure if the `navItems` and `paths` are correct. Hopefully this is enough to get us started.
Jira link:
[RSPEED-565](https://issues.redhat.com/browse/RSPEED-565)
> [RSPEED-565] Update deploy config

- src/Components/Lifecycle/Lifecycle.tsx
- src/Components/LifecycleChart/LifecycleChart.tsx
- src/Components/LifecycleTable/LifecycleTable.tsx
WIP
[Old branch](https://github.com/hosekadam/digital-roadmap-frontend/tree/add-interactive-chart-legend)
Jira link:
[RSPEED-518](https://issues.redhat.com/browse/RSPEED-518)
---
---
##
##
> [RSPEED-518] Add interactive chart legend

- .tekton/push.yaml
Increase memory for sast-coverity-check.
> Increase memory for sast-coverity-check

- src/Components/Lifecycle/Lifecycle.tsx
> fix(Lifecycle): Fix error that crept in via rebase

- src/Components/Lifecycle/Lifecycle.tsx
- src/Components/Upcoming/Upcoming.tsx
- src/api.ts
Jira link:
[RSPEED-519](https://issues.redhat.com/browse/RSPEED-519)
---
---
##
##
> [RSPEED-519] Set up Lifecycle and Upcoming error states

- CONTRIBUTING.md
- deploy/frontend.yaml
- fec.config.js
- package-lock.json
- package.json
- src/utils/utils.ts
Remove the “digital-“ prefix. Getting the name to line up with what is needed to expose the service.
Jira link:
[RSPEED-629](https://issues.redhat.com/browse/RSPEED-629)
> Change package name

- fec.config.js
- package-lock.json
- package.json
- src/Components/Lifecycle/Lifecycle.tsx
- src/Components/Lifecycle/filteringUtils.ts
- src/Components/LifecycleChart/LifecycleChart.tsx
- src/Components/LifecycleFilters/LifecycleFilters.tsx
- src/Components/LifecycleTable/LifecycleTable.tsx
- src/Routing.tsx
- src/__mocks__/mockData.ts
- src/types/Stream.ts
- src/utils/utils.ts
This PR adapts the Lifecycle page to the new format of the backend appstream data. An update was also made so any null dates get converted to "Not available" so our data conforms to one standard. 
Jira link:
---
---
##
##
> Update appstream data

- package.json
Adding this change following ConsoleDOT onboard guide
https://inscope.corp.redhat.com/docs/default/Component/consoledot-pages/containerized-frontends/migration/#step-2-disable-jest-cache-in-packagejson
Jira link:
[RSPEED-813](https://issues.redhat.com/browse/RSPEED-813)
---
---
##
##
> [RSPEED-813] Update test in package.json

- deploy/frontend.yaml
Set the correct navItems that match how the application is configured.
Jira link:
[RSPEED-629](https://issues.redhat.com/browse/RSPEED-629)
> [RSPEED-629] Update nav items in template

- .tekton/pull-request.yaml
- .tekton/push.yaml
Update application and component names as well as git repo.
Jira link:
[RSPEED-895](https://issues.redhat.com/browse/RSPEED-895)
> [RSPEED-895] Update pipelines

- deploy/frontend.yaml
[RSPEED-895](https://issues.redhat.com/browse/RSPEED-895)
> [RSPEED-896] Change default image

- .tekton/pipeline-build.yaml
> Update Konflux references

- src/Components/Lifecycle/Lifecycle.tsx
- src/Components/Upcoming/Upcoming.tsx
- src/Components/UpcomingTable/UpcomingTable.tsx
- src/Components/UpcomingTable/UpcomingTableFilters.tsx
- src/types/Filter.ts
- src/utils/utils.ts
Add shared filter data structure. Update UI components to update filters and URL when selected. Update page to read URL on first load and update filters/data structure.
Jira link:
[RSPEED-839](https://issues.redhat.com/browse/RSPEED-839)
---
---
##
##
> feat(Upcoming): Add URL updates

- deploy/frontend.yaml
- package-lock.json
- package.json
This PR migrates the routes defined in fed-modules.json to the frontend.yaml file for Digital Roadmap. feoConfigEnabled has been set to True.
---
##
##
> Migrate fed modules to frontend yaml file

- src/Components/Lifecycle/Lifecycle.tsx
- src/Components/LifecycleChart/LifecycleChart.tsx
- src/Components/LifecycleChartSystem/LifecycleChart.scss
- src/Components/LifecycleChartSystem/LifecycleChartSystem.tsx
- src/__mocks__/mockData.ts
- src/types/SystemLifecycleChanges.ts
Jira link:
[RSPEED-600](https://issues.redhat.com/browse/RSPEED-600)
---
---
##
##
> [RSPEED-600, RSPEED-908] Add loading support status from API

- src/Components/Lifecycle/Lifecycle.tsx
- src/Components/LifecycleChart/LifecycleChart.tsx
- src/Components/LifecycleChartSystem/LifecycleChartSystem.tsx
- src/__mocks__/mockData.ts
Added responsive behavior to the LifecycleChart component to properly handle browser zoom events and window resizing. A ResizeObserver was added to dynamically track container dimensions and event listeners for both resize and zoom browser events were added. 
Jira link:
---
---
##
##
> Add dynamic chart width

- deploy/testing-integration.yml
Update the IQE metadata in the test integration file to better filter the set of tests we want to run in the automated test runs.
Jira link:
[RSPEED-911](https://issues.redhat.com/browse/RSPEED-XXX)
---
##
##
> RSPEED-911 Update some IQE metadata for automatic triggered tests

- src/Components/Lifecycle/Lifecycle.tsx
This PR updates the filterData component to check the name attribute that contains the entered text inside the search box instead of the state variable that required a second character entry to be updated. 
Jira link:
[RSPEED-966](https://issues.redhat.com/browse/RSPEED-966)
---
---
##
##
> Update the name filter to check actual filter param

- src/Routes/LifecyclePage/LifecyclePage.tsx
- src/Routes/UpcomingPage/UpcomingPage.tsx
This PR updates our  "subject to change" messages for Life Cycle and Roadmap pages after discussions with the legal team
Jira link:
[RSPEED-1044](https://issues.redhat.com/browse/RSPEED-1044)
---
---
##
##
> Revise 'subject to change' messages for Life Cycle and Roadmap pages

- src/Components/LifecycleChart/LifecycleChart.tsx
This PR updates the chart line color to #151515
Jira link:
[RSPEED-1081(https://issues.redhat.com/browse/RSPEED-1081)
---
---
##
##
> [RSPEED-1081] Update chartline color to #151515

- src/Components/Upcoming/Upcoming.tsx
This PR removes the capitalization from the comments in the roadmap cards. 
Jira link:
[RSPEED-1083](https://issues.redhat.com/browse/RSPEED-1083)
---
---
##
##
> [RHEL-1083] Remove capitalization from comment in roadmap cards

- .prettierrc
- eslint.config.mjs
Add config file for prettier to keep same formatting for all developers in the team.
Jira link:
---
---
##
##
> Add prettierrc file

- src/Components/LifecycleModalWindow/LifecycleModalWindow.scss
- src/Components/LifecycleModalWindow/LifecycleModalWindow.tsx
- src/Components/LifecycleTable/LifecycleTable.tsx
- src/Components/UpcomingRow/UpcomingRow.tsx
- src/__mocks__/mockData.ts
Jira link:
[RSPEED-826](https://issues.redhat.com/browse/RSPEED-826)
---
---
##
##
> [RSPEED-826] Add a modal view for systems in Lifecycle Tab

- src/Components/LifecycleModalWindow/LifecycleModalWindow.tsx
Jira link:
[RSPEED-1151](https://issues.redhat.com/browse/RSPEED-1151)
---
---
##
##
> [RSPEED-1152] Add URL generation for system in modal window

- src/Components/LifecycleModalWindow/LifecycleModalWindow.tsx
- src/__mocks__/mockData.ts
This PR adds pagination to the modal view shown when clicking systems in the Lifecycle and Roadmap tabs. Styling has also been added so they match the mocks in Figma.
Jira link:
[RSPEED-1155](https://issues.redhat.com/browse/RSPEED-1155)
---
---
##
##
> [RSPEED-1155] Modal pagination and styling

- src/Routes/LifecyclePage/LifecyclePage.tsx
- src/Routes/UpcomingPage/UpcomingPage.tsx
This PR updates the styling for the alerts message in the Roadmap and Lifecycle tabs. The variant line has been removed as well as the shadows. Padding has been adjusted to match mocks.
Jira link:
---
---
##
##
> Update Alert styling

- deploy/frontend.yaml
Update group for Roadmap in Observibility and Monitoring 
Jira link:
---
---
##
##
> Add searchEntries and sericeTiles to frontend.yaml

- src/api.ts
Jira link:
[RSPEED-1079](https://issues.redhat.com/browse/RSPEED-1079)
---
---
##
##
> [RSPEED-1079] Improve api error message

- src/Components/LifecycleChart/LifecycleChart.tsx
- src/Components/LifecycleChartSystem/LifecycleChartSystem.tsx
This PR updates the chartBar tooltips to display to the right with a arrow tipped tooltip box. The tooltip for the chartLine has been kept the same with the mouse tracking events. 
Jira link:
---
---
##
##
> Tooltip style update

- src/Components/Lifecycle/Lifecycle.tsx
- src/Components/LifecycleFilters/LifecycleFilters.test.tsx
- src/Components/LifecycleFilters/LifecycleFilters.tsx
- src/__mocks__/mockData.ts
- src/constants.ts
- src/types/Stream.ts
- src/types/SystemLifecycleChanges.ts
Jira link:
[RSPEED-1169](https://issues.redhat.com/browse/RSPEED-1169)
---
---
##
##
> [RSPEED-1169] Add installed&related data

- src/Components/LifecycleFilters/LifecycleFilters.tsx
This PR disables the sort by for the chart on systems when in the All view. This is because we don't work with the systems field in the All view
Jira link:
---
---
##
##
> Disable system sort

- src/Components/LifecycleChart/LifecycleChart.tsx
- src/Components/LifecycleChartSystem/LifecycleChartSystem.tsx
This PR fixes the large gaps in between chart items when there are many total items.
Jira link:
---
---
##
##
> [RSPEED-1248] Fix chart gaps

- src/Components/LifecycleChart/LifecycleChart.tsx
- src/Components/LifecycleChartSystem/LifecycleChartSystem.tsx
This PR filters out the "Not installed" type from our Chart legend when the all view is selected. This is because there will be no "Not installed" type when in the all view.
Jira link:
---
---
##
##
> Hide not installed legend when viewFilter is all

- src/Components/Lifecycle/Lifecycle.tsx
Filters out null minor fields from the all systems api 
Jira link:
---
---
##
##
> Filter null minor fields in the All systems data

- src/Components/LifecycleTable/LifecycleTable.tsx
Add icons for the systems column for both lifecycle appstreams and systems. Account for padding when there is no icon so everything is inline. 
Jira link:
---
---
##
##
> Add icons to the Systems column for lifecycle

- src/Routes/LifecyclePage/LifecyclePage.tsx
- src/Routes/UpcomingPage/UpcomingPage.tsx
This PR adds info icons next to the headers of the Life Cycle and Roadmap tab. 
Jira link:
---
---
##
##
> Add info icons

- src/Components/LifecycleTable/LifecycleTable.tsx
This PR updates the key used for sorting the appstream table so it doesn't create a bug where one item remains at the top of the table when switching views.
Jira link:
[RSPEED-1473](https://issues.redhat.com/browse/RSPEED-1473)
---
---
##
##
> [RSPEED-1473] Create a unique key for the appstream table

- src/Components/Upcoming/Upcoming.tsx
Adds caching and update when we show noDataAvailable
Jira link:
---
---
##
##
> Caching and update when we show noDataAvailable

- src/Components/LifecycleTable/LifecycleTable.tsx
Creates a unique key to remove the bug with appstream data leaking into the system lifecycle data for the table
Jira link:
---
---
##
##
> Create a unique key for rendering system lifecycle table data

- src/Components/Lifecycle/Lifecycle.tsx
- src/Components/Upcoming/Upcoming.tsx
In case of reaching unimplemented workspace filtering, show to the users better message.
Jira link:
---
https://github.com/user-attachments/assets/f6a5d72e-f435-4966-ae51-1fe7fd86a950
---
##
##
> Add locked state for workspace filtering

- deploy/testing-integration.yml
As per now, only the critical tests are 100% green, the high test cases are missing a few fixes. Until they are fixed I'd like to have a green pipeline, thus I'm temporally removing the high priority test cases from the filter.
Jira link:
[RSPEED-1026](https://issues.redhat.com/browse/RSPEED-1026)
---
##
##
> Temporally only run critical integration tests

- src/Components/Lifecycle/Lifecycle.tsx
Jira link:
[RSPEED-1646](https://issues.redhat.com/browse/RSPEED-1646)
---
---
##
##
> [RSPEED-1646] Make API calls parallel

- src/Components/Lifecycle/Lifecycle.tsx
- src/Components/Upcoming/Upcoming.tsx
- src/api.ts
- src/types/ErrorObject.ts
Jira link:
[RSPEED-1642](https://issues.redhat.com/browse/RSPEED-1642)
---
---
##
##
> [RSPEED-1642] Improve timeout message

- src/Components/Lifecycle/Lifecycle.tsx
This reverts commit 0a2a74c1abe6ff9c0c44edfbc972e40a92bcf0c4.
Jira link:
---
---
##
##
> Revert "Race condition prevention in Lifecycle API calls (#179)"

- src/Components/LifecycleChart/LifecycleChart.test.tsx
- src/Components/LifecycleChart/LifecycleChart.tsx
- src/Components/LifecycleChartSystem/LifecycleChartSystem.test.tsx
- src/Components/LifecycleChartSystem/LifecycleChartSystem.tsx
- src/Components/UpcomingRow/UpcomingRow.tsx
- src/utils/utils.test.ts
- src/utils/utils.ts
- test/jest.setup.js
Adds IDs to the Life Cycle chart bars to later select the elements properly at E2E tests.
Jira link:
[RSPEED-1788](https://issues.redhat.com/browse/RSPEED-1788)
---
---
##
##
> Add data attributes to rendered bar elements

- .tekton/pipeline-build.yaml
- Dockerfile
Use `SOURCE_DATE_EPOCH` when creating the container image. Set `SOURCE_DATE_EPOCH` to the date of the latest commit in the build pipeline to ensure consistent builds.
> Use SOURCE_DATE_EPOCH for setting image creation

- deploy/testing-integration.yml
The integration test pipeline has errors regarding selenium session stopped working. My main concern it is rounning out of memory. In this PR I will try to increase resources and check if the error goes away.
Jira link:
[RSPEED-1794](https://issues.redhat.com/browse/RSPEED-1794)
---
##
##
> [RSPEED-1794] Increase test-integration selenium pod values

- src/Components/LifecycleChart/LifecycleChart.tsx
- src/Components/LifecycleChartSystem/LifecycleChartSystem.tsx
Change date format for lifecycle tooltips to show month and year.
Jira link:
[RSPEED-1137](https://issues.redhat.com/browse/RSPEED-1137)
---
---
##
##
> RSPEED-1137 Change date format for lifecycle tooltips

- src/Components/UpcomingRow/UpcomingRow.test.tsx
- src/Components/UpcomingRow/UpcomingRow.tsx
Change date format for Roadmap table
Jira link:
[RSPEED-1136](https://issues.redhat.com/browse/RSPEED-1136)
---
---
##
##
> [RSPEED-1136] Change date format for Roadmap table
