RedHatInsights/digital-roadmap-frontend

fec.config.js, src/Components/DynamicComponents/DynamicTag.tsx, src/Components/Released/released.scss, src/Components/Released/released.tsx, src/Components/UpcomingTable/UpcomingTable.tsx, src/api.ts, src/constants.ts
Two buttons that make request to backend based on https://github.com/RedHatInsights/digital-roadmap-backend/pull/3
=> RSPEED-270 - Add buttons making requests to backend ith database

src/Components/LifecycleChart/LifecycleChart.tsx, src/Components/LifecycleTable/LifecycleTable.tsx, src/types/Stream.ts
This PR adds the ability for Lifecycle appstreams in the table to be sorted. Sorting for the systems column has been disabled until we get that data inside the api.
Jira link:
---
---
##
##
=> Added sorting for Appstream table

src/Components/LifecycleChart/LifecycleChart.tsx, src/Components/LifecycleTable/LifecycleTable.tsx, src/Components/UpcomingTable/UpcomingTable.tsx, src/Components/UpcomingTable/UpcomingTableFilters.tsx
Clean up lifecycle and upcoming pages.
* Swapped lifecycle pagination positions
* Lifecycle table is compact 
* Lifecycle chart spacing is tighter
* Dropped unused upcoming filter
* Dropped unused header in filtered upcoming
Jira link:
---
---
##
##
=> Clean up lifecycle and upcoming work to better match design

src/Components/Upcoming/Upcoming.tsx, src/Components/UpcomingTable/UpcomingTable.tsx, src/Components/UpcomingTable/UpcomingTableFilters.tsx, src/types/TypeFilter.ts
Clicking cards should trigger filters. Should be able to clear filters with clear button. Clicking a card should override the dropdown.
Switched type to use a Set instead of an array for easier de-duping.
Jira link:
---
https://github.com/user-attachments/assets/7cf9cb71-6335-4289-bc2c-eb19b056f34b
https://github.com/user-attachments/assets/cfec7a1d-8dbf-45bb-ad30-55b339311d7d
---
##
##
=> feat(Upcoming): Add filters

src/Components/Upcoming/Upcoming.tsx, src/Components/UpcomingRow/UpcomingRow.scss, src/Components/UpcomingRow/UpcomingRow.tsx
Added more padding to type style and adjusted header names to reflect Figma.
Jira link:
---
---
##
##
=> fix(Upcoming): Adjust header names and type style

deploy/frontend.yaml
Update the IMAGE value from cloudservices org to redhat-user-workloads/rhel-lightspeed-tenant as new tekton builds land there.
---
---
##
##
=> Update deploy image value

.tekton/pull-request.yaml, .tekton/push.yaml
Use Tekton API v1 term for overriding task resources.
Rename push pipeline to `-on-push` so that we are able to rerun it if the pipeline fails.
=> Update tasks resources and rename pipeline

src/Components/Lifecycle/Lifecycle.tsx
After rebase, dropdowns were not being controlled appropriately. This should make sure that setStates and lifecycle dropdown changes are applied appropriately in filter chain.
Jira link:
---
---
##
##
=> fix(Lifecycle): Fix query param bug

src/Components/UpcomingTable/UpcomingTableFilters.tsx
Prior implementation was not accessible. There were some attempts made at keyboard controls, but native PF dropdowns provide even better support, as well as focus control. I was able to significantly reduce the size and complexity of the file.
Jira link:
---
---
##
##
=> chore(UpcomingTableFilters): Refactor to use PF Dropdown

CONTRIBUTING.md
As the API port got changed due Clowder requirements, default port of the chrome service (now it's used for the API) and of the API needs to be changed.
https://github.com/RedHatInsights/digital-roadmap-backend/pull/61
Jira link:
---
---
##
##
=> Change API and chrome service port

.github/workflows/ci.yaml, .tekton/pull-request.yaml, .tekton/push.yaml
Change default branch name to `main` since this is required by AppSRE with very little flexibility.
=> Change branch name to match AppSRE requirement

src/Components/Lifecycle/Lifecycle.tsx, src/Components/LifecycleFilters/LifecycleFilters.tsx
Add tooltip. Also fixed error I was seeing with new BE.
Jira link:
[RSPEED-905](https://issues.redhat.com/browse/RSPEED-905)
---
---
##
##
=> Add tooltip for export to Lifecycle page

deploy/testing-integration.yml
Remove the "_JAVA_OPTIONS" parameter from the selenium container as it doesn't exist. Also update some hardcoded values to a variable.
Jira link:
[RSPEED-911](https://issues.redhat.com/browse/RSPEED-911)
---
##
##
=> [RSPEED-911] Remove "_JAVA_OPTIONS" var from testing-integration

src/constants.ts
Trailing slashes were removed in the backend API.
[RSPEED-907](https://issues.redhat.com/browse/RSPEED-907)
=> [RSPEED-907] Update API paths

src/Components/Lifecycle/Lifecycle.tsx, src/Components/LifecycleChart/LifecycleChart.tsx, src/Components/LifecycleChartSystem/LifecycleChartSystem.tsx, src/Components/Upcoming/Upcoming.tsx
This PR adds a conditional so the ChartLine component that displays the current timeline is only displayed when data is provided to the chart. Additionally empty states have been added for when there is no Roadmap or Lifecycle data returned from a successful api call.
Jira link:
[RSPEED-921](https://issues.redhat.com/browse/RSPEED-921)
---
---
##
##
=> Hide chart current timeline when no data is given

src/Components/FilterComponents/LifecycleDropdown.tsx, src/Components/Lifecycle/Lifecycle.tsx, src/Components/Lifecycle/filteringUtils.test.ts, src/Components/Lifecycle/filteringUtils.ts
This PR adds a dropdown for the RHEL 8 Application Streams and ensures it functions with the existing routing and filtering configuration. The filteringUtils tests have also been updated to accommodate the new changes.
Jira link:
[RSPEED-1021](https://issues.redhat.com/browse/RSPEED-1021)
---
---
##
##
=> [RSPEED-1021] RHEL 8 application streams dropdown

src/Components/LifecycleChart/LifecycleChart.tsx, src/Components/LifecycleChartSystem/LifecycleChartSystem.tsx
This PR adds the domainPadding attribute to increase the padding at the top and bottom of the chart. This helps with avoiding unwanted hovering when moving from the chart to the legend and removes the bug where a new line is added to the tooltip of the top and bottom items of the chart. 
Jira link:
[RSPEED-1036](https://issues.redhat.com/browse/RSPEED-1036)
---
---
##
##
=> [RSPEED-1036] Add domainPadding to Lifecycle chart

src/Components/LifecycleChart/LifecycleChart.tsx, src/Components/LifecycleChartSystem/LifecycleChartSystem.tsx
This PR removes the VoronoiContainer dependency while maintaining tooltip functionality so we don't see the tooltip display when not hovering an active item
Summary of additions:
- Replaced PatternFly's VoronoiContainer with custom tooltip implementation
- Added direct event handlers to chart elements for mouse interactions
- Implemented cursor-following tooltip using fixed positioning
- Maintained the same tooltip content and styling as original implementation
- Improved hover state visual feedback for bars and current date line
Jira link:
[RSPEED-1034](https://issues.redhat.com/browse/RSPEED-1034)
---
---
##
##
=> [RSPEED-1034] Update tooltips to be more responsive 

.tekton/pipeline-build.yaml, .tekton/pull-request.yaml, .tekton/push.yaml, Dockerfile, build/build_app_info.sh, build/server_config_gen.sh, build/universal_build.sh
Changes in the Konflux enterprise contract require moving to a new base image. This in turn meant retooling the existing build pipeline to move away from generating a containerfile to including a containerfile and all accompanying build tools in the repo.
This is ultimately cleaner and something I've been putting off doing for a while.
The image is now built using trusted artifacts instead of workspaces.
=> Update container image build

.prettierrc
printWidth is not max-len, it's something like what you want to see the most. After experimenting, 120 is too much, let's try 115.
Jira link:
---
---
##
##
=> Decrease prettier printWidth

src/Components/Upcoming/Upcoming.tsx, src/Components/UpcomingRow/UpcomingRow.scss, src/Components/UpcomingRow/UpcomingRow.tsx
This PR contains the following changes:
- Increase the width of the "Name" column relative to the the other three columns. 
- Change “Training ticket” to “Tracking ticket”
- Make all three filter cards the same height (equal to the tallest), even if there are a different number of body text lines within them.
Jira link:
[RSPEED-1113](https://issues.redhat.com/browse/RSPEED-1113)
---
---
##
##
=> [RSPEED-1113] Styling roadmap tab

src/Components/LifecycleChart/LifecycleChart.tsx, src/Components/LifecycleChartSystem/LifecycleChartSystem.tsx
This PR adjusts the left padding of the chart based on the longest name in the y axis to accommodate displaying longer names.
Jira link:
[RSPEED-1121](https://issues.redhat.com/browse/RSPEED-1121)
---
---
##
##
=> [RSPEED-1121] Make the left padding of the Chart dynamic

src/Components/Lifecycle/filteringUtils.ts, src/Components/LifecycleTable/LifecycleTable.tsx
This PR fixes the issues with sorting in the Life Cycle table and chart. Main issue was that the new display_name field was not being used in the sorting. Also inverts the sorting for Systems to descending order and disables system sorting when in the All view.
Jira link:
[RSPEED-1181](https://issues.redhat.com/browse/RSPEED-1181)
[RSPEED-1184](https://issues.redhat.com/browse/RSPEED-1184)
---
---
##
##
=> [RSPEED-1181, RSPEED-1184] Fix Life Cycle timeline sort by name

src/Components/Lifecycle/filteringUtils.ts, src/Components/LifecycleTable/LifecycleTable.tsx
This PR adds numeric:true to our localCompare sorting components for RHEL version names. Adding this flag ensures that strings with numbers are sorted properly. 
Jira link:
[RSPEED-1371](https://issues.redhat.com/browse/RSPEED-1371)
---
---
##
##
=> [RSPEED-1371] Add numeric:true to localCompare sorting

src/Components/Upcoming/Upcoming.tsx, src/Components/UpcomingTable/UpcomingTable.tsx, src/Components/UpcomingTable/UpcomingTableFilters.tsx
This PR disables the relevant view in Roadmap when there is no data. Adds a tooltip to the relevant only view describing why it's disabled. Automatically switches to the All view if there is no relevant data. 
Jira link:
---
---
##
##
=> Disable relevant view when there is no relevant data

src/Components/LifecycleChart/LifecycleChart.tsx, src/Components/LifecycleChartSystem/LifecycleChartSystem.tsx
This PR now filters out any hidden item from the chart legend from the current data being supplied to the Chart. There is an issue where if all of the current chart items are hidden then the unhide button stops working. To prevent this conditions have been put in place to prevent the all items but one to be hidden from the chart legend. 
Jira link:
[RSPEED-1228](https://issues.redhat.com/browse/RSPEED-1228)
---
---
##
##
=> [RSPEED-1228] Completely remove chart items when hidden from the legend

src/Components/LifecycleChart/LifecycleChart.tsx, src/Components/LifecycleChartSystem/LifecycleChartSystem.tsx, src/utils/utils.ts
This PR adjusts our code to handle the new "Near retirement" support type that replaces the previous "Support ends within 6 months" and "Support ends within 3 months" types. The original names are still used in the legends. 
Jira link:
---
---
##
##
=> Accept new name for support ends within 3/6 months

src/Components/LifecycleTable/LifecycleTable.tsx
Fix the missing item(specifically `Eclipse RHEL8`) in the Lifecycle Table.
The root cause is that we expect every valid repo to have `application_stream_name`, but it seems `Eclipse RHEL8` have an empty application_stream_name that caused this repo not to be displayed in the table. The `checkDataType()` function was also revised to display the repo with no `application_stream_name`.
Jira link:
[RSPEED-1636](https://issues.redhat.com/browse/RSPEED-1636)
---
---
##
##
=> [RSPEED-1636] Fix missing stream in table

Dockerfile
Create a user account for running caddy in the container image and use that account by default when running the application.
=> Create caddy user

src/Components/Lifecycle/Lifecycle.tsx
This PR fixes the csv file export pushing the "name" variable instead of the full "display_name" variable. This helps users have a clearer view of what packages are in the csv file. 
Jira link:
[RSPEED-1578](https://issues.redhat.com/browse/RSPEED-1578)
---
---
##
##
=> [RSPEED-1578] Improper name display in csv export

src/Components/UpcomingTable/UpcomingTable.tsx
Fixes an issue with the sortData function not sorting Release values properly in the Roadmap tab. Release values were taken in as strings so two digit numbers were not sorted correctly. This PR converts the strings to numbers and separates them into major and minor version so they can be compared correctly. 
Jira link:
[RSPEED-1953](https://issues.redhat.com/browse/RSPEED-1953)
---
---
##
##
=> [RSPEED-1953] Fix sorting by Release in Roadmap tab

src/Components/LifecycleChart/LifecycleChart.tsx, src/Components/LifecycleChartSystem/LifecycleChartSystem.tsx
Add a transparent hit to fix gaps on the legend label of the timeline on the Lifecycle page.
Jira link:
[RSPEED-1074](https://issues.redhat.com/browse/RSPEED-1074)
---
---
##
##
=> [RSPEED-1074] Replace the gap with NBSP to fix the legend hover spacing bug
